# Generated by Django 5.2.5 on 2025-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
