# Generated by Django 5.2.5 on 2025-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assessmentsession_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsession',
            name='current_question',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
