# Generated by Django 5.2.5 on 2025-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_assessmentsession_current_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Option 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Option 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Option 3', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Option 4', max_length=255),
        ),
    ]
