# Generated by Django 5.2.5 on 2025-08-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
    ]
