# Generated by Django 5.2.5 on 2025-08-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_option4_question_answer1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer1',
            new_name='option4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Option 1', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Option 2', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Option 3', max_length=255),
        ),
    ]
