# Generated by Django 5.2.5 on 2025-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_skill_job_description_job_salary_max_job_salary_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamictestquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('questiontext', models.TextField()),
                ('options', models.JSONField()),
                ('order', models.IntegerField()),
                ('isactive', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
