# Generated by Django 5.2.5 on 2025-08-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dynamictestquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamictestquestions',
            old_name='questiontext',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestions',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestions',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestions',
            name='options',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestions',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestions',
            name='updatedat',
        ),
    ]
