# Generated by Django 5.2.5 on 2025-08-27 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_questiontext_dynamictestquestions_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynamicTestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionid', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('questiontext', models.TextField()),
                ('options', models.JSONField()),
                ('order', models.IntegerField()),
                ('isactive', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dynamictestquestions',
            },
        ),
        migrations.DeleteModel(
            name='Dynamictestquestions',
        ),
    ]
