# Generated by Django 5.2.5 on 2025-08-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dynamictestquestion_delete_dynamictestquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictestquestion',
            name='options',
        ),
        migrations.RemoveField(
            model_name='dynamictestquestion',
            name='order',
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='option1',
            field=models.CharField(default='Default Option1', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='option2',
            field=models.CharField(default='Default Option2', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='option3',
            field=models.CharField(default='Default Option3', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='option4',
            field=models.CharField(default='Default Option4', max_length=255),
        ),
    ]
