# Generated by Django 5.2.5 on 2025-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_dynamictestquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictestquestion',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
