# Generated by Django 5.2.5 on 2025-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_dynamictestquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictestquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
