# Generated by Django 5.2.5 on 2025-08-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_dynamictestquestion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictestquestion',
            name='options',
        ),
        migrations.AlterModelTable(
            name='dynamictestquestion',
            table=None,
        ),
    ]
