# Generated by Django 5.2.5 on 2025-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_dynamictestquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dynamictestquestion',
            table='dynamictestquestions',
        ),
    ]
