# Generated by Django 5.2.5 on 2025-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_dynamictestquestion_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictestquestion',
            name='order',
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='option4',
            field=models.CharField(max_length=255),
        ),
    ]
