# Generated by Django 5.2.5 on 2025-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_dynamictestquestion_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterModelTable(
            name='dynamictestquestion',
            table=None,
        ),
    ]
