# Generated by Django 5.2.5 on 2025-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_dynamictestquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictestquestion',
            name='difficulty',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
    ]
