# Generated by Django 5.2.5 on 2025-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_dynamictestquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=''),
        ),
    ]
