# Generated by Django 5.2.5 on 2025-08-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_dynamictestquestion_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictestquestion',
            name='domain',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('interest', 'Interest')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
