# Generated by Django 5.2.5 on 2025-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_dynamictestquestion_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictestquestion',
            name='domain',
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
