# Generated by Django 5.2.5 on 2025-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_dynamictestquestion_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
    ]
