# Generated by Django 5.2.5 on 2025-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_dynamictestquestion_correct_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamictestquestion',
            old_name='category',
            new_name='RoleMapping',
        ),
        migrations.AddField(
            model_name='dynamictestquestion',
            name='skill',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
