# Generated by Django 5.2.5 on 2025-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_category_dynamictestquestion_rolemapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='skill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
