# Generated by Django 5.2.5 on 2025-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_dynamictestquestion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
