# Generated by Django 5.2.5 on 2025-09-01 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_dynamictestquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictestquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
