# Generated by Django 5.1.7 on 2025-09-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_dynamictestquestion_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dynamicTestQuestion',
            new_name='DynamicTechQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
