# Generated by Django 5.2.5 on 2025-09-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_careercategory_careerquestion_careeroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careeroption',
            old_name='role_mapping',
            new_name='RoleMapping',
        ),
    ]
