# Generated by Django 5.2.5 on 2025-09-09 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_role_mapping_careeroption_rolemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSoftSkillsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionid', models.CharField(max_length=50, unique=True)),
                ('skill', models.CharField(default='', max_length=100)),
                ('RoleMapping', models.CharField(max_length=100)),
                ('difficulty', models.CharField(default='easy', max_length=10)),
                ('questiontext', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_option', models.IntegerField(default=1)),
                ('isactive', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
