# Generated by Django 5.2.5 on 2025-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_skillscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='phase',
            field=models.CharField(default='career', max_length=50),
        ),
    ]
