# Generated by Django 5.2.5 on 2025-09-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_assessmentsession_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsession',
            name='phase',
        ),
    ]
