# Generated by Django 5.2.5 on 2025-09-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_assessmentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='soft_question',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='tech_question',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssessmentResult',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
