# Generated by Django 5.2.5 on 2025-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_testresult_soft_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='final_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
