# Generated by Django 5.2.5 on 2025-09-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_skilltestresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilltestresult",
            name="total_score",
            field=models.CharField(max_length=20),
        ),
    ]
