# Generated by Django 5.2.5 on 2025-10-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_academy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academy",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="academy",
            name="last_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="academy",
            name="phone_number",
            field=models.CharField(default="N/A", max_length=20),
        ),
    ]
