# Generated by Django 5.2.5 on 2025-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academy",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="academy",
            name="last_name",
        ),
        migrations.AddField(
            model_name="academy",
            name="name",
            field=models.CharField(default="Unknown Academy", max_length=100),
        ),
        migrations.AlterField(
            model_name="academy",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AlterField(
            model_name="academy",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="academy",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
