# Generated by Django 5.2.5 on 2025-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_remove_academy_first_name_remove_academy_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
