# Generated by Django 5.2.5 on 2025-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_userprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
