# Generated by Django 5.2.5 on 2025-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_userprofile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
