# Generated by Django 5.2.5 on 2025-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_academy_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
