# Generated by Django 5.2.5 on 2025-10-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_userprofile_code_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("verification_code", models.CharField(max_length=6)),
                ("code_expires_at", models.DateTimeField()),
            ],
        ),
    ]
