# Generated by Django 5.2.5 on 2025-10-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_temporaryuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryuser",
            name="code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporaryuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
