# Generated by Django 5.2.5 on 2025-10-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_temporaryuser_code_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="code_expires_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="verification_code",
        ),
    ]
