# Generated by Django 5.2.5 on 2025-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_remove_userprofile_code_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryAcademy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("code_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
