# Generated by Django 5.2.5 on 2025-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_sociallinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
