# Generated by Django 5.2.5 on 2025-11-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_academy_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academy",
            name="user",
        ),
    ]
